### ISSUE TITLE
deserialization of orgid item from User assumes int 

### ISSUE THREAD

**Issue by arturoptophys** [elabftw/elabapi-python#14]
Hello,
when trying out the API I encountered following error. According to documentation ("orgid": "string") the field orgid for User can be any string. In the web interface, a string can be entered in the corresponding field. 
However, when trying to fetch users via python-api using 

```
elabapi_python.UsersApi(api_client)
userapi.read_users()
```
i get an error:
```
Traceback (most recent call last):
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-61ee35d80a4b>", line 1, in <cell line: 1>
    all_users=userapi.read_users()
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api/users_api.py", line 342, in read_users
    (data) = self.read_users_with_http_info(**kwargs)  # noqa: E501
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api/users_api.py", line 395, in read_users_with_http_info
    return self.api_client.call_api(
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 248, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 248, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 618, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 263, in __deserialize
    return self.__deserialize_primitive(data, klass)
  File "/home/artur/miniconda3/envs/DataJoint/lib/python3.9/site-packages/elabapi_python/api_client.py", line 545, in __deserialize_primitive
    return klass(data)
ValueError: invalid literal for int() with base 10: 'e124'
```

I assume the deserialization model assumes this field is an int and cannot deal with strings.

elabapi-python        0.5.0

Best,
Artur

**Comment by NicolasCARPi** [comment]
Hello Artur,

You can tell it to not deserialize with `_preload_content`:

~~~python
users.read_users(_preload_content=False)
~~~

That being said, I'm not sure why this happens in the first place, the api specification has `string` for `orgid`...

**Comment by mhxion** [comment]
> That being said, I'm not sure why this happens in the first place, the api specification has string for orgid...

Maybe this [line](https://github.com/elabftw/elabftw/blob/889f64a7be20d0b33194c5c52f9e93d3bfff4468/apidoc/v2/openapi.yaml#L2809) is the culprit:
```yaml
                     orgid:
                       type: integer
                       nullable: true

```

**Comment by NicolasCARPi** [comment]
Oh I see, the response is not using the `users` component! It's correct in the `users` component but not in the response.

**Comment by mhxion** [comment]
I am glad to see I'm not the only one up at 2AM fiddling with elabapi. ~~You didn't push a fix before me did you :D~~

**Comment by NicolasCARPi** [comment]
@arturoptophys 0.5.1 should be good now!
